version: "3.1"

services:
    site:
        build:
            context: .
            dockerfile: Dockerfile.site
        env_file:
            - .env
        depends_on:
            db_migrate:
                condition: service_completed_successfully
        restart: always

    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        env_file:
            - .env
        depends_on:
            db_migrate:
                condition: service_completed_successfully
        restart: always
