name: Deploy to Production
on:
    push:
        branches:
            - main

jobs:
    bot-docker:
        name: Build and push bot docker image
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Lowercase github repository
              run: echo "REPO=${GITHUB_REPOSITORY@L}" >> "${GITHUB_ENV}"
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile.bot
                  push: true
                  tags: ghcr.io/${{ env.REPO }}/bot:latest,ghcr.io/${{ env.REPO }}/bot:${{ github.sha }}
